NAME = new
CC = gcc
LIBFT = ../../../../libft.a
INCS = ../../../../include/

SRC = new.c



all : 		$(NAME)




$(NAME) :
			@$(CC) $(SRC) $(LIBFT) -o $(NAME)

fclean :
			@rm -rf $(NAME)
			@rm -rf $(OBJ)

.PHONY :	fclean all
